=== ArmerTropf/programming_hs/XML_guenni/2.1a_Projekt.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Projekt (Mitarbeiter+,Team+)>
<!ELEMENT Mitarbeiter (Name, Vorname?, Skill*, Vorgesetzter?)>
<!ELEMENT Name (#PCDATA) >
<!ELEMENT Vorname (#PCDATA) >
<!ELEMENT Skill (#PCDATA) >
<!ELEMENT Team EMPTY >
<!ELEMENT Vorgesetzter (#PCDATA) >
<!ELEMENT Teamleiter (#PCDATA) >

<!ATTLIST Projekt Aufgabe CDATA #REQUIRED >
<!ATTLIST Projekt Zeit CDATA #REQUIRED >
<!ATTLIST Mitarbeiter SchlÃ¼ssel ID #REQUIRED >
<!ATTLIST Team Mitarbeiter IDREFS #REQUIRED >
<!ATTLIST Team Nummer ID #REQUIRED >
<!ATTLIST Team Teilaufgabe CDATA #REQUIRED >
<!ATTLIST Team Teamleiter IDREF #REQUIRED >

=== ArmerTropf/programming_hs/XML_guenni/2.1a_.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Projekt SYSTEM "2.1a_Projekt.dtd">

<Projekt Aufgabe= "Aufgabe_1" Zeit= "100h">
    <Mitarbeiter Schlüssel="a1">
        <Name>Mueller</Name>
        <Skill>Chef</Skill>
    </Mitarbeiter>
    
    <Mitarbeiter Schlüssel="a2">
        <Name>Meier</Name>
        <Vorname>Hans</Vorname>
        
        <Vorgesetzter>Mueller</Vorgesetzter>
    </Mitarbeiter>
    
    <Mitarbeiter Schlüssel="a3">
        <Name>Maler</Name>
        <Vorname>Hugo</Vorname>
        <Skill>Malen</Skill>
        
        <Vorgesetzter>Mueller</Vorgesetzter>
    </Mitarbeiter>
    <Team Nummer="t1" Teilaufgabe="Teilaufgabe_1" Mitarbeiter="a1 a2" Teamleiter= "a3"/>
    <Team Mitarbeiter="a1 a3" Nummer="t2" Teilaufgabe="ta2" Teamleiter="a2"/>
</Projekt>
