=== ArmerTropf/programming_hs/XML_guenni/3.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">  
    
    <xs:element name="START"/>
    <xs:element name="Projekt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Mitarbeiter"   maxOccurs="unbounded"/>
                <xs:element ref="Team" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string"/>
            <xs:attribute name="Aufgabe" type="xs:string"/>
            <xs:attribute name="Ablaufdatum" type="xs:date"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="MitarbeiterSchluessel">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a][1-9])"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Teilaufgabe">
        <xs:restriction base="xs:string">
            <xs:pattern value="([Teilaufgabe]*[_][0-9]*)"/>
        </xs:restriction>
    </xs:simpleType> 
 
    <xs:element name="Mitarbeiter" >
        <xs:complexType>
            <xs:all> 
                <xs:element name="Name" />
                <xs:element name="Vorname" />
                <xs:element name="Skill"/>   
                <xs:element name="Vorgesetzter"/> 
            </xs:all>
            <xs:attribute name="Schluessel" type="MitarbeiterSchluessel"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Team">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="Mitglieder" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Nummer" type="xs:string"/>
            <xs:attribute name="Teilaufgabe" type="Teilaufgabe" />
            <xs:attribute name="Mitarbeiter" type="xs:string"/>
            <xs:attribute name="Teamleiter" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ArmerTropf/programming_hs/XML_guenni/3.3.xml
<?xml version="1.0" encoding="UTF-8"?>
<START  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="3.3.xsd">
    
    <Projekt Name="Optimus" Aufgabe= "Aufgabe_1" Ablaufdatum = "2002-09-24">
        <Mitarbeiter Schluessel="a1" > 
            <Name>Mueller</Name>
            <Vorname/> 
            <Skill>Chef</Skill>
            <Vorgesetzter>Mueller</Vorgesetzter>
        </Mitarbeiter>
        <Mitarbeiter Schluessel="a2">
            <Name>Meier</Name>
            <Vorname/>
            <Skill>Hans</Skill> 
            <Vorgesetzter>Mueller</Vorgesetzter>
        </Mitarbeiter>
        <Mitarbeiter Schluessel="a3">
            <Name>Maler</Name>
            <Vorname>Hugo</Vorname>
            <Skill>Malen</Skill>
            <Vorgesetzter>Mueller</Vorgesetzter>
        </Mitarbeiter>
        <Team Nummer="t1" Teilaufgabe="Teilaufgabe_4" Mitarbeiter="a1 a2 a7" Teamleiter= "a3">
            <Mitglieder>a1</Mitglieder>
            <Mitglieder>a2</Mitglieder>
            <Mitglieder>a7</Mitglieder>            
        </Team>
        <Team Nummer="t2" Teilaufgabe="Teilaufgabe_2" Mitarbeiter="a1 a3" Teamleiter="a2">
            <Mitglieder>a1</Mitglieder>
            <Mitglieder>a3</Mitglieder>
        </Team>
        
    </Projekt>
    <Projekt  Name="Terraform" Aufgabe= "Aufgabe_2" Ablaufdatum = "2018-09-24">
        <Mitarbeiter Schluessel="a1" > 
            <Name>Mueller</Name>
            <Vorname/> 
            <Skill>Chef</Skill>
            <Vorgesetzter>Mueller</Vorgesetzter>
        </Mitarbeiter>
        <Mitarbeiter Schluessel="a2">
            <Name>Meier</Name>
            <Vorname/>
            <Skill>Hans</Skill> 
            <Vorgesetzter>Mueller</Vorgesetzter>
        </Mitarbeiter>
        <Mitarbeiter Schluessel="a3">
            <Name>Maler</Name>
            <Vorname>Hugo</Vorname>
            <Skill>Malen</Skill>
            <Vorgesetzter>Mueller</Vorgesetzter>
        </Mitarbeiter>
        <Team Nummer="t1" Teilaufgabe="Teilaufgabe_4" Mitarbeiter="a1 a2 a7" Teamleiter= "a3">
            <Mitglieder>a1</Mitglieder>
            <Mitglieder>a2</Mitglieder>
            <Mitglieder>a7</Mitglieder>            
        </Team>
        <Team Nummer="t2" Teilaufgabe="Teilaufgabe_2" Mitarbeiter="a1 a3" Teamleiter="a2">
            <Mitglieder>a1</Mitglieder>
            <Mitglieder>a3</Mitglieder>
        </Team>
        
    </Projekt>
</START>
