=== ArmerTropf/programming_hs/XML_guenni/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="Hochschule">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Labor" type="LaborType" minOccurs="1" maxOccurs="unbounded" />
                <xs:element name="Software" type="SoftwareType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            
        </xs:complexType>
        <xs:unique name="LaborID">
            <xs:selector xpath="Labor"></xs:selector>
            <xs:field xpath="@Raumnummer"></xs:field>
        </xs:unique>
        <xs:unique name="ComputerID">
            <xs:selector xpath="Labor/Computer"></xs:selector>
            <xs:field xpath="@Name"></xs:field>
        </xs:unique>
        <xs:key name="SoftwareID">
            <xs:selector xpath="Software"></xs:selector>
            <xs:field xpath="@ID"></xs:field>
        </xs:key>
        <xs:keyref refer="SoftwareID" name="SoftwareIDRef">
            <xs:selector xpath="Labor/Computer/Software"></xs:selector>
            <xs:field xpath="@refID"></xs:field>
        </xs:keyref>
    </xs:element>
    
    <xs:complexType name="LaborType">
        <xs:sequence>
            <xs:element name="Computer" type="ComputerType" minOccurs="1" maxOccurs="unbounded"></xs:element>
            <xs:element name="Scanner" type="ScannerType" minOccurs="0" maxOccurs="unbounded"></xs:element>
            <xs:element name="Drucker" type="DruckerType" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="Raumnummer" type="xs:NCName" use="required"></xs:attribute>
        <xs:attribute name="Name" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="SoftwareType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Beschreibung" type="BeschreibungType" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Besonderheiten" minOccurs="0" maxOccurs="unbounded" type="xs:string" ></xs:element>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:NCName" use="required"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="SoftwareID">
        <xs:attribute name="refID" type="xs:NCName" use="required"></xs:attribute>
        <xs:attribute name="lizensiert" type="xs:boolean" default="true"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="ComputerType">
        <xs:sequence>
            <xs:element name="Betriebssystem" type="xs:string" minOccurs="1" maxOccurs="1" />            
            <xs:element name="Beschaffungsdatum" type="xs:date" minOccurs="1" maxOccurs="1" />
            <xs:element name="Erweiterung" type="ErweiterungType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Software" type="SoftwareID" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Beschreibung" type="BeschreibungType" minOccurs="1" maxOccurs="1" />
            <xs:element name="Besonderheiten" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="Name" type="xs:NCName" use="required"></xs:attribute>
    </xs:complexType>
   
    <xs:complexType name="ScannerType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Beschaffungsdatum" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Beschreibung" type="BeschreibungType" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DruckerType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Beschaffungsdatum" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Beschreibung" type="BeschreibungType" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ErweiterungType">
        <xs:sequence>
            <xs:element name="Beschreibung" type="BeschreibungType" minOccurs="1" maxOccurs="1" />
            <xs:element name="Besonderheit" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="BeschreibungType" mixed="true">
        <xs:sequence>
            <xs:element name="Hersteller" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Abstrakte ComplexTypes 
    <xs:complexType name="DeviceType">
        <xs:sequence>
            <xs:element name="Beschreibung" type="BeschreibungType"></xs:element>
            <xs:element name="Beschaffungsdatum" type="xs:date"></xs:element>
        </xs:sequence>
        <xs:attribute name="Name" type="xs:NCName" use="required"></xs:attribute>
    </xs:complexType>
    -->
</xs:schema>

=== ArmerTropf/programming_hs/XML_guenni/Assignment1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Stylesheet.xsl"?>
<Hochschule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Schema.xsd">
   <Labor Raumnummer="Z2301" Name="Labor01">
      <Computer Name="Rechner01">
         <Betriebssystem>Windows 7</Betriebssystem>
         <Beschaffungsdatum>2010-01-01</Beschaffungsdatum>
         <Erweiterung>
            <Beschreibung>2. Festplatte von
               <Hersteller>Seagate</Hersteller>
            </Beschreibung>
         </Erweiterung>
         <Erweiterung>
            <Beschreibung>3. Festplatte von
               <Hersteller>WD</Hersteller>
            </Beschreibung>
         </Erweiterung>
         <Software refID="Office2007"/>
         <Beschreibung>Rechner von
            <Hersteller>Aldi</Hersteller>
         </Beschreibung>
         <Besonderheiten>Gehäuse stark beschädigt</Besonderheiten>
      </Computer>
      <Computer Name="Rechner02">
         <Betriebssystem>Windows 8</Betriebssystem>
         <Beschaffungsdatum>2012-01-01</Beschaffungsdatum>
         <Erweiterung>
            <Beschreibung>4GB zusätzlicher RAM von
               <Hersteller>Samsung</Hersteller>
            </Beschreibung>
         </Erweiterung>
         <Software refID="Office2007"/>
         <Software refID="PhotoshopCS5"/>
         <Beschreibung>Rechner von
            <Hersteller>Media-Markt</Hersteller>
         </Beschreibung>
         <Besonderheiten>Motherboard wurde bereis mehrfach getauscht</Besonderheiten>
      </Computer>
      <Computer Name="Rechner03">
         <Betriebssystem>Windows 10</Betriebssystem>
         <Beschaffungsdatum>2014-01-01</Beschaffungsdatum>
         <Erweiterung>
            <Beschreibung>zusätzliche Graphikkarte von
               <Hersteller>Gigabyte</Hersteller>
            </Beschreibung>
         </Erweiterung>
         <Software refID="Office2007"/>
         <Software refID="PhotoshopCS5"/>
         <Software refID="Office365"/>
         <Beschreibung> Rechner von
            <Hersteller>Real</Hersteller>
         </Beschreibung>
      </Computer>
      <Drucker>
         <Name>DeskJet</Name>
         <Beschaffungsdatum>2011-01-01</Beschaffungsdatum>
         <Beschreibung>Drucker von
            <Hersteller>HP</Hersteller>
         </Beschreibung>
      </Drucker>
      
   </Labor>
   
   <Labor Raumnummer="Z2302" Name="Labor02">
      <Computer Name="Rechner04">
         <Betriebssystem>Windows 10</Betriebssystem>
         <Beschaffungsdatum>2014-01-01</Beschaffungsdatum>
         <Erweiterung>
            <Beschreibung>zusätzliche SSD von
               <Hersteller>Samsung</Hersteller>
            </Beschreibung>
         </Erweiterung>
         <Software refID="Office2007"/>
         <Software refID="PhotoshopCS5"/>
         <Software refID="Office365"/>
         <Beschreibung> Rechner von
            <Hersteller>Real</Hersteller>
         </Beschreibung>
      </Computer>
   </Labor>
   <Labor Raumnummer="u" Name="f">
      <Computer Name="h">
         <Betriebssystem></Betriebssystem>
         <Beschaffungsdatum>2011-11-11</Beschaffungsdatum>
         <Beschreibung>
            <Hersteller></Hersteller>
         </Beschreibung>
      </Computer>
   </Labor>
   <Labor Raumnummer="g" Name="">
      <Computer Name="v">
         <Betriebssystem></Betriebssystem>
         <Beschaffungsdatum>2010-11-11</Beschaffungsdatum>
         <Beschreibung>
            <Hersteller></Hersteller>
         </Beschreibung>
      </Computer>
   </Labor>
   
   
   
   <Software ID="Office2007">
      <Name>Microsoft Office 2007</Name>
      <Beschreibung>
         Software von
         <Hersteller>Microsoft</Hersteller>
      </Beschreibung>
      <Besonderheiten></Besonderheiten>
   </Software>
   
   <Software ID="Office2010">
      <Name>Microsoft Office 2010</Name>
      <Beschreibung>
         <Hersteller>Microsoft</Hersteller>
      </Beschreibung>
   </Software>
   
   <Software ID="Office365"> 
      <Name>Microsoft Office 365</Name>
      <Beschreibung>
         <Hersteller>Microsoft</Hersteller>
      </Beschreibung>
   </Software>
   
   <Software ID="PhotoshopCS5">
      <Name>Photoshop CS5</Name>
      <Beschreibung>Test
         <Hersteller>Adobe</Hersteller>
      </Beschreibung>
      <Besonderheiten>Fntgmgj</Besonderheiten>
   </Software>
   
</Hochschule>
